source ENV['GEM_SOURCE'] || 'https://rubygems.org'
case RUBY_PLATFORM
when /darwin/
  gem 'CFPropertyList'
end
gem 'puppet', '5.3.5'
gem 'facter', '2.4.6'
gem 'rubocop', '0.47.1'
gem 'acustomgemthatmustbemanuallyfixed', '6.6.6'
gem 'rspec-puppet-facts', '1.7.0'

# Workaround for PDOC-160
gem 'puppet-strings', :git => 'https://github.com/puppetlabs/puppet-strings'
gem 'pdqtest', '1.1.0'
