#!/usr/bin/env ruby
require 'rubygems'
ruby_have = Gem::Version.new(RUBY_VERSION)
ruby_need = Gem::Version.new('2.2.0')

if (ruby_have <=> ruby_need) == -1
  raise "Please upgrade Ruby to at least #{ruby_need.version}"
end


require 'pdqtest'
require 'pdqtest/emoji'
require 'pdqtest/instance'
require 'pdqtest/rspec'
require 'pdqtest/util'
require 'pdqtest/skeleton'
require 'pdqtest/lint'
require 'pdqtest/syntax'
require 'pdqtest/core'
require 'pdqtest/upgrade'
require 'escort'

# display help if nothing specified
ARGV.push('-h') if ARGV.empty?

Escort::App.create do |app|
  app.version PDQTest::VERSION
  app.summary "pdqtest"
  app.description "test puppet code quickly"

  app.options do |opts|
    opts.opt(:keep_container,
      'Leave container running?',
      :long     => '--keep-container',
      :type     => :boolean,
      :default  => false,
    )

    opts.opt(:disable_emoji,
      'Do not display emoji status characters',
      :long     => '--disable-emoji',
      :type     => :boolean,
      :default  => false,
    )
  end

  app.command :all do |command|
    command.summary "All"
    command.description "Run all tests"
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])

      PDQTest::Instance.set_keep_container(options[:global][:options][:keep_container])
      PDQTest::Core.run([
        lambda {PDQTest::Syntax.puppet},
        lambda {PDQTest::Lint.puppet},
        lambda {PDQTest::Rspec.run},
        lambda {PDQTest::Instance.run},
      ])
    end
  end

  app.command :rspec do |command|
    command.summary "RSpec"
    command.description "Run the RSpec tests"
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Core.run(lambda {PDQTest::Rspec.run})
    end
  end


  app.command :acceptance do |command|
    command.summary "Acceptance"
    command.description "Run the acceptance (Docker) tests"
    command.options do |opts|
      opts.opt(:example,
        'Run only this example (eg --example examples/init.pp)',
        :long     => '--example',
        :type     => :string,
        :default  => nil,
      )
    end
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Instance.set_keep_container(options[:global][:options][:keep_container])
      example = options[:global][:commands][:acceptance][:options][:example]
      PDQTest::Core.run(lambda {PDQTest::Instance.run(example)})
    end
  end

  app.command :init do |command|
    command.summary "Initialise testing"
    command.description "Install skeleton testing configuration into this module"
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Skeleton.init
    end
  end

  app.command :generate_rspec do |command|
    command.summary "Generate RSpec"
    command.description "For each class in the module, generate basic RSpec tests"
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Rspec.gen_specs
    end
  end

  app.command :generate_acceptance do |command|
    command.summary "Generate Acceptance test"
    command.description "Create a testcase in /examples and the corresponding files for acceptance testing"
    command.options do |opts|
      opts.opt(:example,
        'Generate only this example (eg --example examples/newtest.pp)',
        :long     => '--example',
        :type     => :string,
        :default  => nil,
      )
    end
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      example = options[:global][:commands][:generate_acceptance][:options][:example]

      PDQTest::Skeleton.generate_acceptance(example)
    end
  end


  app.command :shell do |command|
    command.summary "Shell"
    command.description "Open a shell inside a docker container identical to the test environment before anything has run"
    command.action do |options, arguments|
      PDQTest::Instance.shell
    end
  end

  app.command :syntax do |command|
    command.summary "Syntax"
    command.description "Check for syntax errors"
    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Core.run(lambda {PDQTest::Syntax.puppet})
    end
  end

  app.command :lint do |command|
    command.summary "Lint"
    command.description "Check for lint errors"

    command.action do |options, arguments|
      PDQTest::Emoji.disable(options[:global][:options][:disable_emoji])
      PDQTest::Core.run(lambda {PDQTest::Lint.puppet})
    end
  end

  app.command :setup do |command|
    command.summary "Setup"
    command.description "Install the docker container required for testing"

    command.action do |options, arguments|
      PDQTest::Core.run(lambda {
        system("docker pull #{PDQTest::Docker::IMAGE_NAME}")
      })
    end
  end

  app.command :info do |command|
    command.summary "Info"
    command.description "Print info about this module"
    command.action do |options, arguments|
      PDQTest::Puppet.info
    end
  end


  app.command :upgrade do |command|
    command.summary "Upgrade"
    command.description "Upgrade the current module to use this version of PDQTest"
    command.action do |options, arguments|
      PDQTest::Upgrade.upgrade
    end
  end
end
