#!/usr/bin/env ruby
require 'pdqtest/instance'
require 'pdqtest/rspec'
require 'pdqtest/skeleton'
require 'pdqtest/lint'
require 'pdqtest/syntax'
require 'pdqtest/core'
require 'escort'

# display help if nothing specified
ARGV.push('-h') if ARGV.empty?

Escort::App.create do |app|
  app.version PDQTest::VERSION
  app.summary "pdqtest"
  app.description "test puppet code quickly"

  app.options do |opts|
    opts.opt(:keep_container,
      'Leave container running?',
      :long     => '--keep-container',
      :type     => :boolean,
      :default  => false,
    )
  end

  app.command :all do |command|
    command.action do |options, arguments|
      PDQTest::Instance.set_keep_container(options[:global][:options][:keep_container])
      PDQTest::Core.run([
        lambda {PDQTest::Syntax.puppet},
        lambda {PDQTest::Lint.puppet},
        lambda {PDQTest::Rspec.run},
        lambda {PDQTest::Instance.run},
      ])
    end
  end

  app.command :rspec do |command|
    command.action do |options, arguments|
      PDQTest::Core.run(lambda {PDQTest::Rspec.run})
    end
  end


  app.command :acceptance do |command|
    command.options do |opts|
      opts.opt(:example,
        'Run only this example (eg --example examples/init.pp)',
        :long     => '--example',
        :type     => :string,
        :default  => nil,
      )
    end
    command.action do |options, arguments|
      PDQTest::Instance.set_keep_container(options[:global][:options][:keep_container])
      example = options[:global][:commands][:acceptance][:options][:example]
      PDQTest::Core.run(lambda {PDQTest::Instance.run(example)})
    end
  end

  app.command :init do |command|
    command.action do |options, arguments|
      PDQTest::Skeleton.init
    end
  end

  app.command :shell do |command|
    command.action do |options, arguments|
      PDQTest::Instance.shell
    end
  end

  app.command :syntax do |command|
    command.action do |options, arguments|
      PDQTest::Core.run(lambda {PDQTest::Syntax.puppet})
    end
  end

  app.command :lint do |command|
    command.action do |options, arguments|
      PDQTest::Core.run(lambda {PDQTest::Lint.puppet})
    end
  end

  app.command :setup do |command|
    command.action do |options, arguments|
      PDQTest::Core.run(lambda {
        system("docker pull #{PDQTest::Docker::IMAGE_NAME}")
      })
    end
  end

  app.command :info do |command|
    command.action do |options, arguments|
      PDQTest::Puppet.info
    end
  end

end
