#!/usr/bin/env ruby
require 'quicktest/instance'
require 'quicktest/rspec'
require 'quicktest/skeleton'
require 'escort'

# display help if nothing specified
ARGV.push('-h') if ARGV.empty?

Escort::App.create do |app|
  app.version Quicktest::VERSION
  app.summary "quicktest"
  app.description "test puppet code quickly"

  app.options do |opts|
    opts.opt(:keep_container,
      'Leave container running?',
      :long     => '--keep-container',
      :type     => :boolean,
      :default  => false,
    )
  end

  app.command :all do |command|
    command.action do |options, arguments|
      Quicktest::Instance.set_keep_container(options[:global][:options][:keep_container])
      
      if Quicktest::Rspec.run and Quicktest::Instance.run
        puts "finished - tests ok :)"
      else
        abort("finished - THERE ARE TEST FAILURES :()")
      end
    end
  end

  app.command :rspec do |command|
    command.action do |options, arguments|
      Quicktest::Rspec.run
    end
  end


  app.command :acceptance do |command|
    command.action do |options, arguments|
      Quicktest::Instance.set_keep_container(options[:global][:options][:keep_container])
      if Quicktest::Instance.run
        puts "finished - tests ok :)"
      else
        abort("finished - THERE ARE TEST FAILURES :()")
      end
    end
  end

  app.command :init do |command|
    command.action do |options, arguments|
      Quicktest::Skeleton.init
    end
  end

  app.command :shell do |command|
    command.action do |options, arguments|
      Quicktest::Instance.shell
    end
  end
end
